languageCode = "en"
languageName = "English"
weight = 1
title = "@toytag.net"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "Mon, Jan 2, 2006"
  # logo = "logo.png"
  # secondaryLogo = "logo.png"
  description = "Zhenzhong \"Anthony\" Tang's Odyssey: Portfolio, Blog, and Beyond"
  copyright = "Copy, _right?_ ü§î <br> &copy; { year } Zhenzhong Tang"

[params.author]
  name = "Zhenzhong \"Anthony\" Tang"
  image = "img/me.jpg"
  headline = "Software Engineer üßë‚Äçüíª @ Arista Networks <br> CIS Alumni @ UPenn"
  bio = "Code, Debug, Rewrite, Repeat"
  links = [
    { linkedin = "https://www.linkedin.com/in/zhenzhong-anthony-tang-82334a210" },
    { instagram = "https://instagram.com/toytag12" },
    { github = "https://github.com/toytag" },
  ]
