languageCode = "zh-cn"
languageName = "ä¸­æ–‡"
weight = 2
title = "@toytag.net"

[params]
  displayName = "ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "logo.png"
  # secondaryLogo = "logo.png"
  # description = "Zhenzhong \"Anthony\" Tang's Odyssey: Portfolio, Blog, and Beyond"
  # copyright = "Copy, _right?_ :thinking_face: <br> &copy; { year } Zhenzhong Tang"

[params.author]
  name = "æ±¤æŒ¯ä¸­"
  image = "img/me.jpg"
  headline = "Arista Networks ç¨‹åºçŒ¿ ğŸ’ <br> UPenn CIS æ ¡å‹"
  bio = "ç å†œè‡ªå­¦æˆæ‰"
  links = [
    { linkedin = "https://www.linkedin.com/in/zhenzhong-anthony-tang-82334a210" },
    { instagram = "https://instagram.com/toytag12" },
    { github = "https://github.com/toytag" },
  ]
